spring:
  kafka:
    bootstrap-servers: ec2-18-235-150-53.compute-1.amazonaws.com:9092

app:
  topic:
    foo: bigDataRequestTopic

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG